# Generated by Django 5.0.4 on 2024-04-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
            bases=('patient.patient',),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patient.patient')),
                ('is_head_of_department', models.BooleanField(default=False)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.department')),
                ('speciality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.speciality')),
            ],
            options={
                'abstract': False,
            },
            bases=('patient.patient',),
        ),
    ]
