# Generated by Django 5.0.4 on 2024-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_branchadministrator_table_alter_doctor_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='room_number',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='position',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
