# Generated by Django 5.0.4 on 2024-09-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_speciality_room_number_alter_speciality_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='room_number',
        ),
        migrations.AddField(
            model_name='doctor',
            name='room_number',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
