# Generated by Django 5.0 on 2024-02-17 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_doctor_doctor_remove_doctor_id_and_more'),
        ('user_authentication', '0004_alter_baseuser_inn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Staff',
        ),
    ]
