# Generated by Django 5.0 on 2024-01-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='individual_unique_number',
            new_name='inn',
        ),
    ]
