# Generated by Django 5.0.4 on 2024-05-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_remove_address_postal_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
        migrations.AlterModelTable(
            name='emergencycontact',
            table='EmergencyContact',
        ),
    ]
