# Generated by Django 5.0 on 2024-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_alter_baseuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
