# Generated by Django 5.0.4 on 2024-09-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_alter_address_table_alter_emergencycontact_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='standarduser',
            name='is_patient',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
