# Generated by Django 5.0 on 2024-02-25 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0007_alter_baseuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_user', to='user_authentication.address'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(default='gdZGnGf3', max_length=128),
        ),
    ]
