# Generated by Django 5.0.2 on 2024-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0010_alter_baseuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
