# Generated by Django 5.0.4 on 2024-08-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('patient', '0003_patient_allergies_patient_blood_group_and_more'),
        ('staff', '0003_speciality_room_number_alter_speciality_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staff.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
