# Generated by Django 5.0.4 on 2024-08-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_complaint_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_referral',
            field=models.BooleanField(default=False),
        ),
    ]
