# Generated by Django 5.0.4 on 2024-08-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_is_referral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='complaint',
            new_name='reason',
        ),
    ]
