# Generated by Django 5.0.4 on 2024-08-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_rename_complaint_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Ожидание приема'), ('in_progress', 'На приеме'), ('completed', 'Выписан'), ('canceled', 'Отменен'), ('critical', 'Критический')], default='booked', max_length=20),
        ),
    ]
