# Generated by Django 5.0.4 on 2024-09-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_status'),
        ('staff', '0004_remove_speciality_room_number_doctor_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='referral_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_appointments', to='staff.doctor'),
        ),
    ]
