# Generated by Django 5.0.4 on 2024-09-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_referral_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_referral',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='referral_doctor',
        ),
        migrations.CreateModel(
            name='ReferralAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
        ),
    ]
