# Generated by Django 5.0.4 on 2024-09-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_appointment_is_referral_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referralappointment',
            table='Referral Appointment',
        ),
    ]
