# Generated by Django 5.0.4 on 2024-09-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_referralappointment_table'),
        ('staff', '0004_remove_speciality_room_number_doctor_room_number'),
        ('treatment', '0014_remove_treatment_referral_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralappointment',
            name='referral_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.doctor'),
        ),
        migrations.AddField(
            model_name='referralappointment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment'),
        ),
    ]
