# Generated by Django 5.0.4 on 2024-08-12 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.TextField()),
                ('frequency', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_condition', models.CharField(choices=[('satisfactory', 'Удовлетворительное'), ('relatively_satisfactory', 'Относительно удовлетворит'), ('moderate_severity', 'Средней тяжести'), ('severe', 'Тяжелое')], max_length=50)),
                ('consciousness', models.CharField(choices=[('clear', 'Ясное'), ('slowed', 'Заторможенное'), ('absent', 'Отсутствует'), ('oriented', 'Ориентирован'), ('disoriented', 'Не ориентирован')], max_length=50)),
                ('position', models.CharField(choices=[('active', 'Активное'), ('inactive', 'Неактивное')], max_length=50)),
                ('skin_condition', models.CharField(choices=[('normal', 'Обычной окраски'), ('pale', 'Бледные')], max_length=50)),
                ('edema', models.CharField(choices=[('yes', 'Есть'), ('no', 'Нет')], max_length=50)),
                ('edema_comments', models.TextField(blank=True, null=True)),
                ('nail_condition', models.CharField(choices=[('dry', 'Сухие'), ('dull', 'Тусклые'), ('brittle', 'Ломкие'), ('healthy', 'Здоровые')], max_length=50)),
                ('joint_condition', models.CharField(choices=[('unchanged', 'Внешне не изменены'), ('full_movement', 'Движение в полном объеме'), ('painful', 'Болезненны')], max_length=50)),
                ('joint_comments', models.TextField(blank=True, null=True)),
                ('lymph_nodes', models.CharField(choices=[('not_enlarged', 'Не увеличены'), ('enlarged', 'Увеличены'), ('fused', 'Спаяны с окружающей тканью'), ('not_fused', 'Не спаяны'), ('painful', 'Болезненны'), ('painless', 'Безболезненны')], max_length=100)),
                ('nasal_breathing', models.CharField(choices=[('free', 'Свободное'), ('difficult', 'Затрудненное'), ('discharge', 'Выделения')], max_length=50)),
                ('chest_participation', models.CharField(choices=[('symmetrical', 'Симметрично'), ('lags_right', 'Отстает справа'), ('lags_left', 'Отстает слева')], max_length=50)),
                ('muscle_participation', models.CharField(choices=[('neck', 'Шеи'), ('intercostal', 'Межреберий'), ('intercostal_retraction', 'Втяжение межреберий'), ('shoulder_girdle', 'Плечевого пояса')], max_length=100)),
                ('lung_auscultation', models.CharField(choices=[('vesicular', 'Везикулярное'), ('harsh', 'Жесткое'), ('weakened', 'Ослабленное')], max_length=50)),
                ('heart_area', models.CharField(choices=[('unchanged', 'Не изменен'), ('cardiac_hump', 'Имеется сердечный горб')], max_length=50)),
                ('pericardial_pulsation', models.CharField(choices=[('present', 'Есть'), ('absent', 'Нет'), ('pronounced', 'Выраженное')], max_length=50)),
                ('epigastric_pulsation', models.CharField(choices=[('present', 'Есть'), ('absent', 'Нет'), ('pronounced', 'Выраженное')], max_length=50)),
                ('cyanosis', models.CharField(choices=[('none', 'Нет'), ('acrocyanosis', 'Акроцианоз'), ('diffuse', 'Диффузный'), ('mild', 'Легкий'), ('moderate', 'Умеренный'), ('severe', 'Выраженный')], max_length=50)),
                ('neck_veins', models.CharField(choices=[('present', 'Есть'), ('absent', 'Нет')], max_length=50)),
                ('heart_tones', models.CharField(choices=[('rhythmic', 'Ритмичные'), ('arrhythmia', 'Аритмия')], max_length=50)),
                ('systolic_murmur', models.CharField(choices=[('present', 'Есть'), ('absent', 'Нет')], max_length=50)),
                ('diastolic_murmur', models.CharField(choices=[('present', 'Есть'), ('absent', 'Нет')], max_length=50)),
                ('oral_mucosa', models.CharField(choices=[('normal', 'Обычной окраски'), ('pale', 'Бледная')], max_length=50)),
                ('tongue', models.CharField(choices=[('dry', 'Сухой'), ('clean', 'Чистый'), ('coated', 'Обложен')], max_length=50)),
                ('pharynx', models.CharField(choices=[('hyperemic', 'Гиперемирован'), ('normal', 'Обычной окраски')], max_length=50)),
                ('tonsils', models.CharField(choices=[('enlarged', 'Увеличены'), ('not_enlarged', 'Не увеличены')], max_length=50)),
                ('abdomen', models.CharField(choices=[('normal_size', 'Обычных размеров'), ('soft', 'Мягкий'), ('painful', 'Болезненный'), ('painless', 'Безболезненный')], max_length=100)),
                ('abdomen_comments', models.TextField(blank=True, null=True)),
                ('liver', models.CharField(choices=[('enlarged', 'Увеличен'), ('not_enlarged', 'Не увеличен')], max_length=50)),
                ('gallbladder', models.CharField(choices=[('palpable', 'Пальпируется'), ('not_palpable', 'Не пальпируется')], max_length=50)),
                ('stool', models.CharField(choices=[('regular', 'Регулярный'), ('constipation', 'Запоры'), ('loose', 'Жидкий')], max_length=50)),
                ('stool_comments', models.TextField(blank=True, null=True)),
                ('urination', models.CharField(choices=[('free', 'Свободное'), ('difficult', 'Затрудненное'), ('painful', 'Болезненное'), ('clear', 'Прозрачное'), ('cloudy', 'Мутное'), ('small_amount', 'Мало'), ('large_amount', 'Много')], max_length=100)),
                ('urination_comments', models.TextField(blank=True, null=True)),
                ('tapping_symptom', models.CharField(choices=[('negative', 'Отрицательный'), ('positive_right', 'Положительный справа'), ('positive_left', 'Положительный слева')], max_length=50)),
                ('neurological_status', models.CharField(choices=[('good', 'Воспринимает хорошо'), ('reduced', 'Снижено'), ('lost', 'Утрачено')], max_length=50)),
                ('eye_slits', models.CharField(choices=[('equal', 'Одинаковые'), ('ptosis_right', 'Птоз справа'), ('ptosis_left', 'Птоз слева'), ('half_ptosis', 'Полуптоз')], max_length=50)),
                ('face', models.CharField(choices=[('symmetrical', 'Симметричное'), ('flattened', 'Сглаженность')], max_length=50)),
                ('dizziness', models.CharField(choices=[('none', 'Нет'), ('present', 'Есть'), ('systemic', 'Системное')], max_length=50)),
                ('meningeal_symptoms', models.CharField(choices=[('negative', 'Отрицательные'), ('positive', 'Положительные')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_conclusion', models.TextField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_plan', models.TextField(blank=True, null=True)),
                ('lab_tests', models.FileField(blank=True, null=True, upload_to='labs/')),
                ('justification_and_formulation', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('medications', models.ManyToManyField(blank=True, related_name='treatments', to='treatment.medications')),
                ('objective_examination', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.objectiveexamination')),
                ('referral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treatment.referral')),
            ],
        ),
    ]
