# Generated by Django 5.0.4 on 2024-08-12 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
