# Generated by Django 5.0.4 on 2024-08-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('treatment', '0002_alter_treatment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
