# Generated by Django 5.0.4 on 2024-08-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_alter_referral_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectiveexamination',
            name='abdomen',
            field=models.CharField(blank=True, choices=[('normal_size', 'Обычных размеров'), ('soft', 'Мягкий'), ('painful', 'Болезненный'), ('painless', 'Безболезненный')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='chest_participation',
            field=models.CharField(blank=True, choices=[('symmetrical', 'Симметрично'), ('lags_right', 'Отстает справа'), ('lags_left', 'Отстает слева')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='consciousness',
            field=models.CharField(blank=True, choices=[('clear', 'Ясное'), ('slowed', 'Заторможенное'), ('absent', 'Отсутствует'), ('oriented', 'Ориентирован'), ('disoriented', 'Не ориентирован')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='cyanosis',
            field=models.CharField(blank=True, choices=[('none', 'Нет'), ('acrocyanosis', 'Акроцианоз'), ('diffuse', 'Диффузный'), ('mild', 'Легкий'), ('moderate', 'Умеренный'), ('severe', 'Выраженный')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='diastolic_murmur',
            field=models.CharField(blank=True, choices=[('present', 'Есть'), ('absent', 'Нет')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='dizziness',
            field=models.CharField(blank=True, choices=[('none', 'Нет'), ('present', 'Есть'), ('systemic', 'Системное')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='edema',
            field=models.CharField(blank=True, choices=[('yes', 'Есть'), ('no', 'Нет')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='epigastric_pulsation',
            field=models.CharField(blank=True, choices=[('present', 'Есть'), ('absent', 'Нет'), ('pronounced', 'Выраженное')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='eye_slits',
            field=models.CharField(blank=True, choices=[('equal', 'Одинаковые'), ('ptosis_right', 'Птоз справа'), ('ptosis_left', 'Птоз слева'), ('half_ptosis', 'Полуптоз')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='face',
            field=models.CharField(blank=True, choices=[('symmetrical', 'Симметричное'), ('flattened', 'Сглаженность')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='gallbladder',
            field=models.CharField(blank=True, choices=[('palpable', 'Пальпируется'), ('not_palpable', 'Не пальпируется')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='general_condition',
            field=models.CharField(blank=True, choices=[('satisfactory', 'Удовлетворительное'), ('relatively_satisfactory', 'Относительно удовлетворит'), ('moderate_severity', 'Средней тяжести'), ('severe', 'Тяжелое')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='heart_area',
            field=models.CharField(blank=True, choices=[('unchanged', 'Не изменен'), ('cardiac_hump', 'Имеется сердечный горб')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='heart_tones',
            field=models.CharField(blank=True, choices=[('rhythmic', 'Ритмичные'), ('arrhythmia', 'Аритмия')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='joint_condition',
            field=models.CharField(blank=True, choices=[('unchanged', 'Внешне не изменены'), ('full_movement', 'Движение в полном объеме'), ('painful', 'Болезненны')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='liver',
            field=models.CharField(blank=True, choices=[('enlarged', 'Увеличен'), ('not_enlarged', 'Не увеличен')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='lung_auscultation',
            field=models.CharField(blank=True, choices=[('vesicular', 'Везикулярное'), ('harsh', 'Жесткое'), ('weakened', 'Ослабленное')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='lymph_nodes',
            field=models.CharField(blank=True, choices=[('not_enlarged', 'Не увеличены'), ('enlarged', 'Увеличены'), ('fused', 'Спаяны с окружающей тканью'), ('not_fused', 'Не спаяны'), ('painful', 'Болезненны'), ('painless', 'Безболезненны')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='meningeal_symptoms',
            field=models.CharField(blank=True, choices=[('negative', 'Отрицательные'), ('positive', 'Положительные')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='muscle_participation',
            field=models.CharField(blank=True, choices=[('neck', 'Шеи'), ('intercostal', 'Межреберий'), ('intercostal_retraction', 'Втяжение межреберий'), ('shoulder_girdle', 'Плечевого пояса')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='nail_condition',
            field=models.CharField(blank=True, choices=[('dry', 'Сухие'), ('dull', 'Тусклые'), ('brittle', 'Ломкие'), ('healthy', 'Здоровые')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='nasal_breathing',
            field=models.CharField(blank=True, choices=[('free', 'Свободное'), ('difficult', 'Затрудненное'), ('discharge', 'Выделения')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='neck_veins',
            field=models.CharField(blank=True, choices=[('present', 'Есть'), ('absent', 'Нет')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='neurological_status',
            field=models.CharField(blank=True, choices=[('good', 'Воспринимает хорошо'), ('reduced', 'Снижено'), ('lost', 'Утрачено')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='oral_mucosa',
            field=models.CharField(blank=True, choices=[('normal', 'Обычной окраски'), ('pale', 'Бледная')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='pericardial_pulsation',
            field=models.CharField(blank=True, choices=[('present', 'Есть'), ('absent', 'Нет'), ('pronounced', 'Выраженное')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='pharynx',
            field=models.CharField(blank=True, choices=[('hyperemic', 'Гиперемирован'), ('normal', 'Обычной окраски')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='position',
            field=models.CharField(blank=True, choices=[('active', 'Активное'), ('inactive', 'Неактивное')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='skin_condition',
            field=models.CharField(blank=True, choices=[('normal', 'Обычной окраски'), ('pale', 'Бледные')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='stool',
            field=models.CharField(blank=True, choices=[('regular', 'Регулярный'), ('constipation', 'Запоры'), ('loose', 'Жидкий')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='systolic_murmur',
            field=models.CharField(blank=True, choices=[('present', 'Есть'), ('absent', 'Нет')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='tapping_symptom',
            field=models.CharField(blank=True, choices=[('negative', 'Отрицательный'), ('positive_right', 'Положительный справа'), ('positive_left', 'Положительный слева')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='tongue',
            field=models.CharField(blank=True, choices=[('dry', 'Сухой'), ('clean', 'Чистый'), ('coated', 'Обложен')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='tonsils',
            field=models.CharField(blank=True, choices=[('enlarged', 'Увеличены'), ('not_enlarged', 'Не увеличены')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='objectiveexamination',
            name='urination',
            field=models.CharField(blank=True, choices=[('free', 'Свободное'), ('difficult', 'Затрудненное'), ('painful', 'Болезненное'), ('clear', 'Прозрачное'), ('cloudy', 'Мутное'), ('small_amount', 'Мало'), ('large_amount', 'Много')], max_length=100, null=True),
        ),
    ]
