# Generated by Django 5.0.4 on 2024-08-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_alter_objectiveexamination_abdomen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
