# Generated by Django 5.0.4 on 2024-09-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_treatment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('not_complete', 'Not Complete'), ('complete', 'Complete')], default='not_complete', max_length=20),
        ),
    ]
