# Generated by Django 5.0.4 on 2024-09-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_treatment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='conclusion_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
