# Generated by Django 5.0.4 on 2024-09-19 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_speciality_room_number_doctor_room_number'),
        ('treatment', '0007_referral_conclusion_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='staff.doctor'),
        ),
    ]
