# Generated by Django 5.0.4 on 2024-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_referral_referral_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('pending_final_update', 'Pending Final Update'), ('complete', 'Complete')], default='in_progress', max_length=20),
        ),
    ]
