# Generated by Django 5.0.4 on 2024-09-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0009_alter_treatment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='conclusion_updated_at',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referral_doctor',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='status',
        ),
    ]
