# Generated by Django 5.0.4 on 2024-09-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_speciality_room_number_doctor_room_number'),
        ('treatment', '0011_treatment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='is_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='referral_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_treatments', to='staff.doctor'),
        ),
    ]
