# Generated by Django 5.0.4 on 2024-09-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_referralappointment_table'),
        ('treatment', '0012_treatment_is_referral_treatment_referral_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.referralappointment'),
        ),
    ]
