# Generated by Django 5.0.4 on 2024-09-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0013_referral_referral_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='referral_doctor',
        ),
    ]
