# Generated by Django 5.0.4 on 2024-09-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0014_remove_treatment_referral_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referral_appointment',
        ),
    ]
