# Generated by Django 5.0.4 on 2024-09-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_referralappointment_referral_doctor_and_more'),
        ('treatment', '0015_remove_referral_referral_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='referral_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_ref_appointment', to='appointment.referralappointment'),
        ),
    ]
