# Generated by Django 5.0.4 on 2024-05-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "standarduser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user_authentication.standarduser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("user_authentication.standarduser",),
        ),
    ]
