# Generated by Django 5.0.4 on 2024-06-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
    ]
