# Generated by Django 5.0.4 on 2024-05-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
    ]
