# Generated by Django 5.0.4 on 2024-08-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_allergy_pill_vaccine'),
        ('patient', '0002_alter_patient_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(related_name='patients', to='hospital.allergy'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(default='UNK', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='vaccines',
            field=models.ManyToManyField(related_name='patients', to='hospital.vaccine'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vision',
            field=models.CharField(default='UNK', max_length=50),
        ),
    ]
