# Generated by Django 5.0 on 2023-12-27 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_address_remove_patient_address_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_2', to='patient.address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_2', to='patient.emergencycontact'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patient.address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_1', to='patient.address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_1', to='patient.emergencycontact'),
        ),
    ]
