# Generated by Django 5.0 on 2023-12-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_address_2_patient_emergency_contact_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address_2',
        ),
    ]
