# Generated by Django 5.0 on 2024-02-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_emergencycontact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='secondary_emergency_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_emergency_contact', to='patient.emergencycontact'),
        ),
    ]
