# Generated by Django 5.0 on 2023-12-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_address_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_1', to='patient.address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_1', to='patient.emergencycontact'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_2', to='patient.emergencycontact'),
        ),
    ]
