# Generated by Django 5.0 on 2023-12-27 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_address_1_and_more'),
        ('user_authentication', '0003_address_baseuser_date_of_birth_baseuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_1', to='user_authentication.address'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='user_authentication.address'),
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
