# Generated by Django 5.0.2 on 2024-03-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_secondary_emergency_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='address',
        ),
    ]
