# Generated by Django 5.0 on 2024-01-12 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patient_address_1_and_more'),
        ('user_authentication', '0003_address_baseuser_date_of_birth_baseuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_1', to='user_authentication.address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_1', to='patient.emergencycontact'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_2', to='patient.emergencycontact'),
        ),
    ]
