# Generated by Django 5.0 on 2024-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_insurance_name', models.CharField(max_length=64)),
                ('insurance_policy_id', models.IntegerField()),
                ('insurance_package_type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=64)),
                ('glasses_contact_lenses', models.CharField(choices=[('YWG', 'Wears Glasses'), ('YWCL', 'Wears Contact Lenses'), ('N', 'No')], default='N', max_length=64)),
                ('vaccination_status', models.CharField(max_length=128)),
                ('allergies', models.CharField(max_length=512)),
                ('medicine', models.CharField(max_length=512)),
                ('other_health_issues', models.CharField(max_length=512)),
            ],
        ),
    ]
