# Generated by Django 5.0.4 on 2024-06-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_branch_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='phone_numbers',
        ),
        migrations.AddField(
            model_name='branch',
            name='phone_numbers',
            field=models.ManyToManyField(null=True, related_name='branch', to='hospital.branchphonenumber'),
        ),
    ]
