# Generated by Django 5.0.4 on 2024-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_branch_phone_numbers_branch_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='branch', to='hospital.branchphonenumber'),
        ),
    ]
