# Generated by Django 5.0.4 on 2024-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_branch_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('diagnostic_method', models.TextField()),
                ('treatment_method', models.TextField()),
                ('types', models.CharField()),
                ('restrictions', models.TextField()),
            ],
            options={
                'db_table': 'Allergy',
            },
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('purpose', models.TextField()),
                ('composition', models.TextField()),
                ('indications', models.TextField()),
                ('contraindications', models.TextField()),
                ('side_effects', models.TextField()),
                ('special_instructions', models.TextField()),
                ('dosage_and_administration', models.TextField()),
                ('storage_conditions', models.TextField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'Pill',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('contraindications', models.TextField()),
                ('reaction', models.TextField()),
                ('composition', models.TextField()),
                ('diseases_prevention', models.TextField()),
                ('symptoms', models.TextField()),
            ],
            options={
                'db_table': 'Vaccine',
            },
        ),
    ]
